# Lab 2

In [40]:
class Tester:
    def testCase1():
        try:
            assert('df' in globals()), "You do not have a DataFrame called `df`."
            assert(len(df) == 64048 ), "This is not the right dataframe"
            print("Test Passed: \u2714")
        except AssertionError as msg:
            print("-"*10 + " ERROR " + "-"*10)
            print(msg)
    def testCase2():
        try:
            assert('df_STAT' in globals()), "You do not have a DataFrame called `df_STAT`."
            assert('df_CS' in globals()), "You do not have a DataFrame called `df_CS`."
            assert( (df_STAT["Subject"] == "STAT").all()), "df_STAT has non-STAT courses in it"
            assert( (df_CS["Subject"] == "CS").all()), "df_CS has non-CS courses in it"
            assert(len(df_STAT) == len(df[df["Subject"] == "STAT"])), "df_STAT was not created correctly"
            assert(len(df_CS) == len(df[df["Subject"] == "CS"])), "df_CS was not created correctly"
            print("Test Passed: \u2714")
        except AssertionError as msg:
            print("-"*10 + " ERROR " + "-"*10)
            print(msg)
            
    def testCase3():
        try:
            assert('average_percentage_STAT' in globals()), "You do not have a DataFrame called `average_percentage_STAT`."
            assert('average_percentage_CS' in globals()), "You do not have a DataFrame called `average_percentage_CS`."
            assert(average_percentage_STAT == df_STAT["Percentage of As"].mean()), "`average_percentage_STAT` was not calculated correctly"
            assert(average_percentage_CS == df_CS["Percentage of As"].mean()), "`average_percentage_CS` was not calculated correctly"
            print("Test Passed: \u2714")
        except AssertionError as msg:
            print("-"*10 + " ERROR " + "-"*10)
            print(msg)        
    def testCase4():
        try:
            assert('df_cs_recent' in globals()), "You do not have a DataFrame called `df_cs_recent`."
            assert('df_cs_old' in globals()), "You do not have a DataFrame called `df_cs_old`."
            assert('df_stat_recent' in globals()), "You do not have a DataFrame called `df_stat_recent`."
            assert('df_stat_old' in globals()), "You do not have a DataFrame called `df_stat_old`."
            ans1 = df_CS[df_CS["Year"] >= 2021]
            ans2 = df_CS[df_CS["Year"] < 2021]
            ans3 = df_STAT[df_STAT["Year"] >= 2021]
            ans4 = df_STAT[df_STAT["Year"] < 2021]
            assert((df_cs_recent["Year"] >= 2021).all() and df_cs_recent["Subject"]=="CS").all(), "`df_cs_recent` dataframe is not correct"
            assert((df_cs_old["Year"] < 2021).all() and df_cs_old["Subject"]=="CS").all(), "`df_cs_old` dataframe is not correct"
            assert((df_stat_recent["Year"] >= 2021).all() and df_stat_recent["Subject"]=="STAT").all(), "`df_stat_recent` dataframe is not correct"
            assert((df_stat_old["Year"] < 2021).all() and df_stat_old["Subject"]=="STAT").all(), "`df_stat_old` dataframe is not correct"
            assert(len(df_cs_recent) == len(ans1)), "`df_cs_recent` dataframe is not correct"
            assert(len(df_cs_old) == len(ans2)), "`df_cs_old` dataframe is not correct"
            assert(len(df_stat_recent) == len(ans3)), "`df_stat_recent` dataframe is not correct"
            assert(len(df_stat_old) == len(ans4)), "`df_stat_old` dataframe is not correct"
            print("Test Passed: \u2714")
        except AssertionError as msg:
            print("-"*10 + " ERROR " + "-"*10)
            print(msg)
    def testCase5():
        try:
            assert('cs_recent_average' in globals()), "You do not have a DataFrame called `cs_recent_average`."
            assert('cs_old_average' in globals()), "You do not have a DataFrame called `cs_old_average`."
            assert('stat_recent_average' in globals()), "You do not have a DataFrame called `stat_recent_average`."
            assert('stat_old_average' in globals()), "You do not have a DataFrame called `stat_old_average`."
            assert(cs_recent_average == df_cs_recent["Percentage of As"].mean()), "`cs_recent_average` was not calculated correctly"
            assert(cs_old_average == df_cs_old["Percentage of As"].mean()), "`cs_old_average` was not calculated correctly"
            assert(stat_recent_average == df_stat_recent["Percentage of As"].mean()), "`stat_recent_average` was not calculated correctly"
            assert(stat_old_average == df_stat_old["Percentage of As"].mean()), "`stat_old_average` was not calculated correctly"
            print("Test Passed: \u2714")
        except AssertionError as msg:
            print("-"*10 + " ERROR " + "-"*10)
            print(msg)

<hr style="color: #DD3403;">

## Load the GPA Dataset

We are going to use the GPA Dataset. It is a list of courses and the grades that were given for each course. The GPA dataset can be found in the following URL:

```
https://evantsiamalos.github.io/material/assignment_1/gpa.csv
```

Use Python to load this dataset into a DataFrame called `df`:

In [5]:
import pandas as pd
df = pd.read_csv("https://evantsiamalos.github.io/material/assignment_1/gpa.csv")
df

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Students,Percentage of As
0,2022,Spring,2022-sp,AAS,100,Intro Asian American Studies,LCD,6,13,0,...,3,0,1,1,0,0,0,"Lee, Sang S",29,0.655172
1,2022,Spring,2022-sp,AAS,100,Intro Asian American Studies,DIS,0,11,5,...,0,1,1,0,0,0,0,"Zheng, Reanne",25,0.640000
2,2022,Spring,2022-sp,AAS,100,Intro Asian American Studies,DIS,0,10,7,...,0,0,0,0,0,2,0,"Zheng, Reanne",27,0.629630
3,2022,Spring,2022-sp,AAS,100,Intro Asian American Studies,DIS,17,8,1,...,0,0,0,0,0,0,0,"Rosado-Torres, Alexander",28,0.928571
4,2022,Spring,2022-sp,AAS,100,Intro Asian American Studies,OD,0,8,4,...,0,0,0,0,1,3,1,"Wang, Yu",21,0.571429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64043,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,1,3,0,0,0,2,1,"Stepanov, Alexei G",31,0.548387
64044,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,"Unger, David",28,0.857143
64045,2010,Summer,2010-su,TAM,212,Introductory Dynamics,LEC,0,1,3,...,1,1,0,2,0,1,0,"Morgan, William T",28,0.142857
64046,2010,Summer,2010-su,TAM,251,Introductory Solid Mechanics,LCD,1,2,2,...,3,2,0,0,1,1,0,"Ott-Monsivais, Stephanie",21,0.238095
64047,2010,Summer,2010-su,TAM,335,Introductory Fluid Mechanics,LEC,5,8,9,...,4,0,0,1,0,2,0,"Keane, Richard D",39,0.564103

### Test Case Checkpoint

In [8]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
# import urllib
# _j = "https://evantsiamalos.github.io/material/assignment_2/assignment2_tester.py"
# _ = urllib.request.urlopen(_j).read()
# exec(_)
Tester.testCase1()

Test Passed: ✔

## The goal of this assignment


We want to investigate a question with this dataset:

- *Is it easier to get an A in STAT or CS courses at UIUC?*

We are going to work with the column called "Percentage of As". This column contains the proportion of: the number of As that the students got in each course divided by the total number of students in each course. 

In order to do so, we are going to find:
- The average percentage of As for STAT.
- The average percentage of As for CS.
- Compare them.

## Question
Why do we use the percentage of As and not the total number of As for each course in the scope of this analysis? 
Write a brief answer in the cell below.

*(✏️ Edit this cell to replace this text with your answer. ✏️)*

# Spliting into STAT and CS
First we are going to split the original dataframe (`df`) into tow smaller dataframes:
- `df_STAT`: The dataframe that contains only the STAT courses.
- `df_CS`: The datafraame that contains only the comouter science courses.

### Subject DataFrames

Select only the rows of the GPA dataset `df` with a `Subject` of `STAT`. Assign these rows to a new DataFrame, `df_STAT`.

In [10]:
df_STAT = df[df["Subject"] == "STAT"]
df_STAT

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Students,Percentage of As
2172,2022,Spring,2022-sp,STAT,100,Statistics,LEC,186,106,55,...,30,10,14,10,8,11,2,"Flanagan, Karle A",582,0.596220
2173,2022,Spring,2022-sp,STAT,100,Statistics,ONL,178,126,72,...,24,19,11,15,12,16,2,"Flanagan, Karle A",663,0.567119
2174,2022,Spring,2022-sp,STAT,100,Statistics,ONL,19,21,4,...,0,3,0,2,2,9,1,"Reger, William J",84,0.523810
2175,2022,Spring,2022-sp,STAT,107,Data Science Discovery,LEC,9,125,24,...,5,2,6,2,1,10,2,"Flanagan, Karle A",230,0.686957
2176,2022,Spring,2022-sp,STAT,200,Statistical Analysis,ONL,57,131,41,...,13,4,2,0,2,9,2,"Fireman, Ellen S",350,0.654286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64040,2010,Summer,2010-su,STAT,100,Statistics,LCD,1,13,3,...,2,2,3,1,1,1,0,"Hirtz, Nathaniel R",39,0.435897
64041,2010,Summer,2010-su,STAT,100,Statistics,LCD,0,14,3,...,3,0,0,1,0,3,1,"Dalpiaz, David M",28,0.607143
64042,2010,Summer,2010-su,STAT,400,Statistics and Probability I,LEC,4,15,7,...,2,2,0,1,0,3,1,"Monrad, Ditlev",47,0.553191
64043,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,1,3,0,0,0,2,1,"Stepanov, Alexei G",31,0.548387
64044,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,"Unger, David",28,0.857143

Select only the rows of the GPA dataset `df` with a `Subject` of `CS`. Assign these rows to a new dataframe, `df_CS`. 
- Make sure your result only contains CS courses!

In [23]:
df_CS = df[df["Subject"] == "CS"]
df_CS

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Students,Percentage of As
712,2022,Spring,2022-sp,CS,101,Intro Computing: Engrg & Sci,OLC,155,340,55,...,3,6,4,6,0,17,1,"Davis, Neal E",642,0.856698
713,2022,Spring,2022-sp,CS,105,Intro Computing: Non-Tech,OLC,12,62,17,...,16,14,3,4,4,9,2,"Zilles, Craig",193,0.471503
714,2022,Spring,2022-sp,CS,105,Intro Computing: Non-Tech,OLC,28,101,26,...,19,20,4,9,2,10,3,"Zilles, Craig",308,0.503247
715,2022,Spring,2022-sp,CS,124,Intro to Computer Science I,OLC,70,314,43,...,9,9,0,18,0,28,4,"Challen, Geoffrey W",578,0.738754
716,2022,Spring,2022-sp,CS,126,Software Design Studio,LCD,47,105,25,...,1,0,1,3,2,5,0,"Woodley, Michael J",203,0.871921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63924,2010,Summer,2010-su,CS,101,Intro Computing: Engrg & Sci,LBD,4,6,2,...,0,1,0,0,0,0,0,"Gambill, Thomas N",21,0.571429
63925,2010,Summer,2010-su,CS,225,Data Structures,LBD,1,5,1,...,3,1,0,2,0,1,0,"Earls, John C",21,0.333333
63926,2010,Summer,2010-su,CS,373,Theory of Computation,LEC,5,1,5,...,0,2,0,2,0,1,1,"Kumar, Viraj",26,0.423077
63927,2010,Summer,2010-su,CS,421,Progrmg Languages & Compilers,LCD,2,5,5,...,1,4,0,4,0,0,1,"Hafiz, Munawar",30,0.400000
63928,2010,Summer,2010-su,CS,598,Object-Oriented Prog & Design,ONL,3,22,0,...,0,0,0,0,0,0,0,"Johnson, Ralph E",30,0.833333

### Test Case Checkpoint

In [24]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.
Tester.testCase2()

Test Passed: ✔

### Comparing the average percentages

Now that we have created `df_STAT` and `df_CS`, we are going to find the **average percentage of As** for each one of them (Hint: You can use the `mean()` function).

In [30]:
average_percentage_STAT = df_STAT["Percentage of As"].mean()
average_percentage_STAT

0.6333807282712893

In [25]:
average_percentage_CS = df_CS["Percentage of As"].mean()
average_percentage_CS

0.5680795951582391

### Test Case Checkpoint

In [31]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
Tester.testCase3()

Test Passed: ✔

## Comparison
Which one of the averages is higher? What does it mean with respect to the question: 

- *Is it easier to get an A in STAT or CS courses at UIUC?*

*(✏️ Edit this cell to replace this text with your answer. ✏️)*

## An Extra Consideration

If you look at the `Year` column of our GPA dataset, you might notice that we have some old data in our set - all the way back to **2010**. . 

If we want to know if it is easier to **currently** get an A in a STAT or CS course, we should control for the **date** of the data by separating into older years and more recent years.

Then we are going to compare the averages for the "old" years, and the averages for the "recent" years.

## Spliting into Old and Recent

Using the code cells below, define four new DataFrames by selecting from rows of our previously created `df_CS` and `df_STAT`. 

- `df_cs_recent`: all `CS` course data in *recent years* ($\space \geq 2021 \space$)
- `df_stat_recent`: all `STAT` course data in *recent years* ($\space \geq 2021 \space$)
- `df_cs_old`: all other, older `CS` course data ($\space < 2021 \space$)
- `df_stat_old`: all other, older `STAT` course data ($\space < 2021 \space$)

Define *recent years* as **any year after and including 2021**, and older years as any year before 2021.

In [32]:
df_stat_recent = df_STAT[df_STAT["Year"] >= 2021]
df_stat_recent

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Students,Percentage of As
2172,2022,Spring,2022-sp,STAT,100,Statistics,LEC,186,106,55,...,30,10,14,10,8,11,2,"Flanagan, Karle A",582,0.596220
2173,2022,Spring,2022-sp,STAT,100,Statistics,ONL,178,126,72,...,24,19,11,15,12,16,2,"Flanagan, Karle A",663,0.567119
2174,2022,Spring,2022-sp,STAT,100,Statistics,ONL,19,21,4,...,0,3,0,2,2,9,1,"Reger, William J",84,0.523810
2175,2022,Spring,2022-sp,STAT,107,Data Science Discovery,LEC,9,125,24,...,5,2,6,2,1,10,2,"Flanagan, Karle A",230,0.686957
2176,2022,Spring,2022-sp,STAT,200,Statistical Analysis,ONL,57,131,41,...,13,4,2,0,2,9,2,"Fireman, Ellen S",350,0.654286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7541,2021,Summer,2021-su,STAT,400,Statistics and Probability I,OLC,11,22,6,...,4,3,2,1,0,7,2,"Nguyen, Ha Khanh",84,0.464286
7542,2021,Summer,2021-su,STAT,410,Statistics and Probability II,ONL,8,14,4,...,3,0,0,3,0,4,2,"Stepanov, Alexey G",56,0.464286
7543,2021,Summer,2021-su,STAT,420,Statistical Modeling in R,ONL,101,94,15,...,1,0,0,0,0,2,4,"Unger, David",227,0.925110
7544,2021,Summer,2021-su,STAT,420,Methods of Applied Statistics,ONL,5,8,1,...,2,0,0,0,0,1,0,"Unger, David",22,0.636364
7545,2021,Summer,2021-su,STAT,425,Applied Regression and Design,ONL,13,13,8,...,0,1,0,0,0,5,0,"Bravo De Guenni, Lelys",45,0.755556

In [33]:
df_cs_recent = df_CS[df_CS["Year"] >= 2021]
df_cs_recent

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Students,Percentage of As
712,2022,Spring,2022-sp,CS,101,Intro Computing: Engrg & Sci,OLC,155,340,55,...,3,6,4,6,0,17,1,"Davis, Neal E",642,0.856698
713,2022,Spring,2022-sp,CS,105,Intro Computing: Non-Tech,OLC,12,62,17,...,16,14,3,4,4,9,2,"Zilles, Craig",193,0.471503
714,2022,Spring,2022-sp,CS,105,Intro Computing: Non-Tech,OLC,28,101,26,...,19,20,4,9,2,10,3,"Zilles, Craig",308,0.503247
715,2022,Spring,2022-sp,CS,124,Intro to Computer Science I,OLC,70,314,43,...,9,9,0,18,0,28,4,"Challen, Geoffrey W",578,0.738754
716,2022,Spring,2022-sp,CS,126,Software Design Studio,LCD,47,105,25,...,1,0,1,3,2,5,0,"Woodley, Michael J",203,0.871921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393,2021,Summer,2021-su,CS,416,Data Visualization,ONL,265,113,25,...,0,0,0,0,0,3,8,"Hart, John C",432,0.932870
7394,2021,Summer,2021-su,CS,421,Progrmg Languages & Compilers,ONL,50,20,5,...,2,0,0,2,0,4,2,"Beckman, Mattox A",92,0.815217
7395,2021,Summer,2021-su,CS,421,Progrmg Languages & Compilers,OLC,17,8,6,...,4,0,0,6,0,5,3,"Beckman, Mattox A",62,0.500000
7396,2021,Summer,2021-su,CS,598,Cloud Capstone,ONL,55,15,3,...,1,0,0,1,0,0,0,"Farivar, Reza",75,0.973333
7397,2021,Summer,2021-su,CS,598,Data Mining Capstone,ONL,11,16,1,...,0,0,0,0,0,0,0,"Farivar, Reza",29,0.965517

In [34]:
df_stat_old = df_STAT[df_STAT["Year"] < 2021]
df_stat_old

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Students,Percentage of As
9790,2020,Fall,2020-fa,STAT,100,Statistics,ONL,402,283,159,...,43,34,15,15,5,35,0,"Flanagan, Karle A",1340,0.629851
9791,2020,Fall,2020-fa,STAT,107,Data Science Discovery,OLC,22,86,13,...,4,4,1,0,0,5,0,"Nguyen, Ha Khanh",163,0.742331
9792,2020,Fall,2020-fa,STAT,200,Statistical Analysis,ONL,26,1,3,...,1,0,3,1,0,1,0,"Ellison, Victoria M",40,0.750000
9793,2020,Fall,2020-fa,STAT,200,Statistical Analysis,ONL,60,112,39,...,9,6,1,4,0,1,0,"Fireman, Ellen S",319,0.661442
9794,2020,Fall,2020-fa,STAT,212,Biostatistics,ONL,50,80,39,...,4,4,1,2,1,1,0,"Findley, Kelly P",242,0.698347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64040,2010,Summer,2010-su,STAT,100,Statistics,LCD,1,13,3,...,2,2,3,1,1,1,0,"Hirtz, Nathaniel R",39,0.435897
64041,2010,Summer,2010-su,STAT,100,Statistics,LCD,0,14,3,...,3,0,0,1,0,3,1,"Dalpiaz, David M",28,0.607143
64042,2010,Summer,2010-su,STAT,400,Statistics and Probability I,LEC,4,15,7,...,2,2,0,1,0,3,1,"Monrad, Ditlev",47,0.553191
64043,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,1,3,0,0,0,2,1,"Stepanov, Alexei G",31,0.548387
64044,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,"Unger, David",28,0.857143

In [46]:
df_cs_old = df_CS[df_CS["Year"] < 2021]
df_cs_old

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Students,Percentage of As
8276,2020,Fall,2020-fa,CS,100,Freshman Orientation,ONL,0,267,2,...,0,0,0,1,0,1,0,"Gunter, Elsa",277,0.971119
8277,2020,Fall,2020-fa,CS,100,Freshman Orientation,OLC,0,17,1,...,0,0,1,0,0,1,0,"Gunter, Elsa",22,0.818182
8278,2020,Fall,2020-fa,CS,101,Intro Computing: Engrg & Sci,OLC,181,191,19,...,2,5,1,1,0,5,0,"Davis, Neal E",434,0.900922
8279,2020,Fall,2020-fa,CS,105,Intro Computing: Non-Tech,OLC,31,105,72,...,20,17,3,2,2,14,0,"Zilles, Craig",420,0.495238
8280,2020,Fall,2020-fa,CS,105,Intro Computing: Non-Tech,OLC,20,45,27,...,4,3,3,2,1,6,0,"Zilles, Craig",174,0.528736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63924,2010,Summer,2010-su,CS,101,Intro Computing: Engrg & Sci,LBD,4,6,2,...,0,1,0,0,0,0,0,"Gambill, Thomas N",21,0.571429
63925,2010,Summer,2010-su,CS,225,Data Structures,LBD,1,5,1,...,3,1,0,2,0,1,0,"Earls, John C",21,0.333333
63926,2010,Summer,2010-su,CS,373,Theory of Computation,LEC,5,1,5,...,0,2,0,2,0,1,1,"Kumar, Viraj",26,0.423077
63927,2010,Summer,2010-su,CS,421,Progrmg Languages & Compilers,LCD,2,5,5,...,1,4,0,4,0,0,1,"Hafiz, Munawar",30,0.400000
63928,2010,Summer,2010-su,CS,598,Object-Oriented Prog & Design,ONL,3,22,0,...,0,0,0,0,0,0,0,"Johnson, Ralph E",30,0.833333

### Test Case Checkpoint

In [47]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.
Tester.testCase4()

Test Passed: ✔

### Puzzle 1.5: New Analysis
Now that we've got all the DataFrames setup with GPA data of the `CS` and `STAT` courses separated by recency (2021 or newer being 'recent'), we can do more in-depth analysis to investigate our question. 

In the following code cells, **calculate the percentages** described by the comment in the cell.

In [52]:
# Percentage of As received in CS in recent years
cs_recent_average = df_cs_recent["Percentage of As"].mean()
print(f'The average Percentage of As received in CS in recent years: {cs_recent_average}')

The average Percentage of As received in CS in recent years: 0.7028313031904205

In [53]:
# Percentage of As received in STAT in recent years
stat_recent_average = df_stat_recent["Percentage of As"].mean()
print(f'The average Percentage of As received in STAT in recent years: {stat_recent_average}')

The average Percentage of As received in STAT in recent years: 0.6693443702142392

In [54]:
# percentage of As received in CS in older years
cs_old_average= df_cs_old["Percentage of As"].mean()
print(f'Percentage of As received in CS in older years: {cs_old_average}')

Percentage of As received in CS in older years: 0.5478218216790133

In [59]:
# percentage of As received in STAT in older years
stat_old_average = df_stat_old["Percentage of As"].mean()
print(f'Percentage of As received in STAT in older years: {stat_old_average}')

Percentage of As received in STAT in older years: 0.6272065190655455

### Test Case Checkpoint

In [60]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
Tester.testCase5()

Test Passed: ✔

### Observe the Results
**Run the following cell** to format all of your answers as a DataFrame.

Keep in mind that "Older" means data from courses **before 2021**, and "Recent" means courses held **during or after 2021**.

In [65]:
pd.DataFrame({
  'Older Average of % of As': [cs_old_average, stat_old_average],
  'Recent Average % of As': [cs_recent_average,stat_recent_average ]
    }, index=['CS', 'STAT'])

      Older Average of % of As  Recent Average % of As
CS                    0.547822                0.702831
STAT                  0.627207                0.669344

Observe that, even though the overall average that we calculated before was greater in STAT, now the recent CS average is higher than the recent STAT average. 


## Question

Why do you think this happens?

*(✏️ Edit this cell to replace this text with your answer. ✏️)*

# Simpson's Paradox

This is **Simpson's Paradox**: a pattern within a population can appear, disappear, or reverse when you look at subpopulations.

In more formal terms, Simpson's Paradox can cause you to observe a pattern reverse when you look at the overall group statistics versus statistics of groups post-stratification. In this case we are stratifying by time.

## Question


Now think about how you respond to the question:
- *Is it easier to get an A in STAT or CS courses at UIUC?*

**Q: Which comparison of percentages do you trust more and why? Are there any other potential confounding variables when answering this question that could be investigated further?.**

*(✏️ Edit this cell to replace this text with your answer. ✏️)*

<hr style="color: #DD3403;">

# Submission
Download your notebook and submit it on Canvas in "**Assignment 2**".